language: node_js
before_script: "make compile"
node_js:
  - 0.4
  - 0.6
notifications:
  irc:
    - "irc.freenode.org#bevry"
    - "irc.freenode.org#docpad"
  email:
    recipients:
      - docpad@bevry.me